Currently Loaded Modulefiles:
  1) anaconda/default
/PHShome/jjd65/prod_of_experts/helper.py:23: RuntimeWarning: overflow encountered in multiply
  out2 = np.array([[(a[i, j]*x[:, i]*x[:, j]*b[i, j])/(b[i, j] + ii*x[:, i]) for j in range(a.shape[0])] for i in range(a.shape[0])])
/PHShome/jjd65/prod_of_experts/helper.py:27: RuntimeWarning: overflow encountered in square
  [a[i, i]*(x[:, i]**2) for i in range(a.shape[0])]))
/PHShome/jjd65/prod_of_experts/spline_learner_poe4d_MM.py:84: RuntimeWarning: overflow encountered in multiply
  self.X1[:,i]*self.X1[:,j])+.01, self.num_knots) for i in range(self.num_bugs)] for j in range(self.num_bugs)])
/PHShome/jjd65/.conda/envs/dispatcher/lib/python3.7/site-packages/numpy/core/function_base.py:153: RuntimeWarning: invalid value encountered in multiply
  y *= step
/PHShome/jjd65/prod_of_experts/spline_learner_poe4d_MM.py:124: RuntimeWarning: invalid value encountered in double_scalars
  bmat[i, ki] = ((xi-self.knots[bug1, bug2][i])*bmat[i, ki-1])/(self.knots[bug1, bug2][i+ki+1-1]-self.knots[bug1, bug2][i]) + (
/PHShome/jjd65/prod_of_experts/spline_learner_poe4d_MM.py:125: RuntimeWarning: invalid value encountered in double_scalars
  (self.knots[bug1, bug2][i+ki+1] - xi)*bmat[i+1, ki-1])/(self.knots[bug1, bug2][i+ki+1]-self.knots[bug1, bug2][i+1])
/PHShome/jjd65/prod_of_experts/spline_learner_poe4d_MM.py:132: RuntimeWarning: overflow encountered in double_scalars
  bmat_mini = np.array([[self.bsplines(X[t,i]*X[t,j], np.array(X),i,j)[:,k-1] for i in range(X.shape[1])] for j in range(X.shape[1])])
Traceback (most recent call last):
  File "./main.py", line 44, in <module>
    main()
  File "./main.py", line 41, in main
    spl.run(gibbs_steps=500)
  File "/PHShome/jjd65/prod_of_experts/spline_learner_poe4d_MM.py", line 458, in run
    mu_theta.squeeze(), sig_theta).rvs()
  File "/PHShome/jjd65/.conda/envs/dispatcher/lib/python3.7/site-packages/scipy/stats/_multivariate.py", line 363, in __call__
    seed=seed)
  File "/PHShome/jjd65/.conda/envs/dispatcher/lib/python3.7/site-packages/scipy/stats/_multivariate.py", line 736, in __init__
    self.cov_info = _PSD(self.cov, allow_singular=allow_singular)
  File "/PHShome/jjd65/.conda/envs/dispatcher/lib/python3.7/site-packages/scipy/stats/_multivariate.py", line 156, in __init__
    s, u = scipy.linalg.eigh(M, lower=lower, check_finite=check_finite)
  File "/PHShome/jjd65/.conda/envs/dispatcher/lib/python3.7/site-packages/scipy/linalg/decomp.py", line 374, in eigh
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/PHShome/jjd65/.conda/envs/dispatcher/lib/python3.7/site-packages/scipy/_lib/_util.py", line 246, in _asarray_validated
    a = toarray(a)
  File "/PHShome/jjd65/.conda/envs/dispatcher/lib/python3.7/site-packages/numpy/lib/function_base.py", line 499, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
