Currently Loaded Modulefiles:
  1) anaconda/default
Traceback (most recent call last):
  File "./main.py", line 44, in <module>
    main()
  File "./main.py", line 40, in main
    DT=args.delta_t,outdir = args.outdir)
  File "/PHShome/jjd65/prod_of_experts/spline_learner_poe4d_MM.py", line 69, in __init__
    self.true_a, self.true_b, self.gr, self.xin, self.dt, self.use_mm, self.mvar, self.pvar*self.dt, self.num_mice, self.num_states)
  File "/PHShome/jjd65/prod_of_experts/helper.py", line 46, in generate_data_MM
    xout = xin + resolution*(xin*r[nn] + michaelis_menten(xin, a, b, ii)) 
  File "/PHShome/jjd65/prod_of_experts/helper.py", line 19, in michaelis_menten
    assert((b == np.ones(a.shape)).all())
AttributeError: 'bool' object has no attribute 'all'
